version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: /api/Dockerfile
    container_name: tfg_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app:Z
      - /var/run/docker.sock:/var/run/docker.sock
